version: '3.4'

services:
  deliveryapi:
    image: ${DOCKER_REGISTRY-}deliveryapi
    build:
      context: .
      dockerfile: DeliveryAPI\Dockerfile

  sqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=RetoBackend*pmolinav*
      - ACCEPT_EULA=Y
    ports:
      - "1440:1433"

